services:
  backend:
    build: ./backend
    environment:
      - FLASK_ENV=production
      - API_HOST=${API_HOST}
    volumes:
      - ${EXT_UPLOAD_FOLDER}:/app/static/uploads
      - ${EXT_DB_FOLDER}:/app/db
      - SECRET_KEY=${SECRET_KEY}

    ports:
      - "5000:5000"  # Expose backend port
    networks:
      - app_network

  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

