
import { Product } from '@/types';

// Mock data for products
export const mockProducts: Product[] = [
  {
    id: '1',
    title: 'Photo Editing Suite Pro',
    description: 'Professional photo editing software with advanced color correction, layer management, and smart object detection.',
    price: 79.99,
    images: ['https://images.unsplash.com/photo-1607706189992-eae578626c86?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80'],
    category: 'design',
    tags: ['photo', 'editing', 'design', 'professional'],
    seller: {
      id: 'seller1',
      name: 'Creative Tools Inc.',
      avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    },
    rating: 4.8,
    reviewCount: 1247,
    featured: true,
    downloadCount: 25689,
    createdAt: new Date('2023-06-15'),
    updatedAt: new Date('2023-12-08'),
  },
  {
    id: '2',
    title: 'Code Productivity Suite',
    description: 'Boost your coding productivity with this comprehensive IDE featuring intelligent code completion, debugging tools, and Git integration.',
    price: 49.99,
    images: ['https://images.unsplash.com/photo-1461749280684-dccba630e2f6?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80'],
    category: 'development-tools',
    tags: ['coding', 'productivity', 'development', 'IDE'],
    seller: {
      id: 'seller2',
      name: 'DevTech Solutions',
      avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    },
    rating: 4.7,
    reviewCount: 867,
    featured: false,
    downloadCount: 18432,
    createdAt: new Date('2023-08-22'),
    updatedAt: new Date('2023-11-30'),
  },
  {
    id: '3',
    title: 'Data Visualization Tool',
    description: 'Create beautiful and interactive data visualizations with this powerful tool. Supports various chart types and data sources.',
    price: 59.99,
    images: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80'],
    category: 'business',
    tags: ['data', 'visualization', 'charts', 'analytics'],
    seller: {
      id: 'seller3',
      name: 'DataViz Pro',
      avatar: 'https://randomuser.me/api/portraits/men/62.jpg',
    },
    rating: 4.5,
    reviewCount: 523,
    featured: false,
    downloadCount: 12754,
    createdAt: new Date('2023-04-10'),
    updatedAt: new Date('2023-10-15'),
  },
  {
    id: '4',
    title: 'Audio Editing Workstation',
    description: 'Professional audio editing software for music producers, podcasters, and sound engineers with advanced mixing capabilities.',
    price: 89.99,
    images: ['https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80'],
    category: 'entertainment',
    tags: ['audio', 'music', 'editing', 'production'],
    seller: {
      id: 'seller4',
      name: 'SoundLab Studios',
      avatar: 'https://randomuser.me/api/portraits/women/28.jpg',
    },
    rating: 4.9,
    reviewCount: 789,
    featured: false,
    downloadCount: 9876,
    createdAt: new Date('2023-07-05'),
    updatedAt: new Date('2023-12-01'),
  },
  {
    id: '5',
    title: 'Task Management Pro',
    description: 'Stay organized with this comprehensive task management software. Features include task tracking, collaboration tools, and progress analytics.',
    price: 29.99,
    images: ['https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80'],
    category: 'productivity',
    tags: ['productivity', 'task management', 'organization'],
    seller: {
      id: 'seller5',
      name: 'Efficiency Labs',
      avatar: 'https://randomuser.me/api/portraits/men/15.jpg',
    },
    rating: 4.6,
    reviewCount: 1045,
    featured: false,
    downloadCount: 21543,
    createdAt: new Date('2023-03-18'),
    updatedAt: new Date('2023-09-20'),
  },
  {
    id: '6',
    title: 'Advanced System Optimizer',
    description: 'Optimize your system performance with this comprehensive utility. Features include disk cleaning, registry repair, and startup optimization.',
    price: 39.99,
    images: ['https://images.unsplash.com/photo-1593642634524-b40b5baae6bb?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80'],
    category: 'utilities',
    tags: ['system', 'optimization', 'cleanup', 'performance'],
    seller: {
      id: 'seller6',
      name: 'TechBoost Systems',
      avatar: 'https://randomuser.me/api/portraits/men/22.jpg',
    },
    rating: 4.4,
    reviewCount: 687,
    featured: false,
    downloadCount: 15432,
    createdAt: new Date('2023-05-25'),
    updatedAt: new Date('2023-11-10'),
  },
];

// Categories data
export const categories = [
  { id: 'design', name: 'Design & Creative', count: 124 },
  { id: 'development-tools', name: 'Development Tools', count: 87 },
  { id: 'business', name: 'Business & Analytics', count: 65 },
  { id: 'productivity', name: 'Productivity', count: 52 },
  { id: 'utilities', name: 'Utilities', count: 43 },
  { id: 'entertainment', name: 'Entertainment', count: 38 },
];
